CREATE PROCEDURE DISPLAY_DETAILS
AS
select * from Employee 
GO;
EXEC DISPLAY_DETAILS;

CREATE PROCEDURE DISPLAY_DETAILS_AT_LOCATION @PLACE nCHAR(30)
AS
select * from Employee WHERE baseLocation=@PLACE
GO
ALTER PROCEDURE DISPLAY_DETAILS_AT_LOCATION @PLACE CHAR(50)
AS
select * from Employee WHERE baseLocation=@PLACE
GO
EXEC DISPLAY_DETAILS_AT_LOCATION 'CHENNAI';

CREATE PROCEDURE INSERTDETAILSDEPARTMENT @IDNUM INT,@DEPT VARCHAR(20)
AS
INSERT INTO [Department name] VALUES (@IDNUM,@DEPT)
GO
EXEC INSERTDETAILSDEPARTMENT 107,'PHY'

CREATE PROCEDURE DISPLAY_ALL_TABLES
AS
SELECT 'DEPARTMENT TABLE'
SELECT *FROM [Department name]
SELECT 'EMPLOYEE TABLE'
SELECT * FROM Employee
SELECT 'STUDENT TABLE'
SELECT * FROM  Student
GO
EXEC DISPLAY_ALL_TABLES

CREATE OR ALTER PROCEDURE SORTBY_COLUMN_ASC @TABLE_NAME VARCHAR(50), @COLUMN_NAME VARCHAR(50)
AS
DECLARE @SUBQUERY VARCHAR(1000);
SET @SUBQUERY='SELECT * FROM '+@TABLE_NAME+' ORDER BY '+@COLUMN_NAME+' ASC'
EXEC(@SUBQUERY)
GO
EXEC SORTBY_COLUMN_ASC 'EMPLOYEE','SALARY'

CREATE OR ALTER PROCEDURE SORTBY_COLUMN_DESC @TABLE_NAME VARCHAR(50), @COLUMN_NAME VARCHAR(50)
AS
DECLARE @SUBQUERY VARCHAR(1000);
SET @SUBQUERY='SELECT * FROM '+@TABLE_NAME+' ORDER BY '+@COLUMN_NAME+' DESC'
EXEC(@SUBQUERY)
GO

EXEC SORTBY_COLUMN_DESC 'EMPLOYEE','SALARY'

CREATE OR ALTER PROCEDURE SORTBY_COLUMN @TABLE_NAME VARCHAR(50), @COLUMN_NAME VARCHAR(50), @SORTBY NCHAR(5)='ASC'
AS
DECLARE @SUBQUERY VARCHAR(1000);
SET @SUBQUERY='SELECT * FROM '+@TABLE_NAME+' ORDER BY '+@COLUMN_NAME+' '+@SORTBY
EXEC(@SUBQUERY)
GO

EXEC SORTBY_COLUMN 'EMPLOYEE','SALARY','DESC'

CREATE OR ALTER PROCEDURE SORTBY_COLUMN @TABLE_NAME VARCHAR(50), @COLUMN_NAME VARCHAR(50), @SORTBY NCHAR(5)='ASC'
AS
DECLARE @SUBQUERY VARCHAR(1000);
SET @SUBQUERY='SELECT * FROM '+@TABLE_NAME+' ORDER BY '+@COLUMN_NAME+' '+@SORTBY
EXEC(@SUBQUERY)
GO

EXEC SORTBY_COLUMN 'EMPLOYEE','SALARY','DESC'

CREATE TYPE EMPLOYEELIST AS TABLE(EMPNAME VARCHAR(50))

CREATE OR ALTER PROCEDURE EMPLOYEE_WITH_SALARY_RANGE (@START INT, @END INT, @EMP_NAME  VARCHAR(MAX) OUTPUT)
AS
SELECT @EMP_NAME = ISNULL(@EMP_NAME + ',', '(') + TRIM(CAST(EMPNAME AS VARCHAR)) FROM Employee WHERE salary>=@START AND salary<=@END
SET @EMP_NAME=TRIM(@EMP_NAME)+')'
GO

DECLARE @OUT VARCHAR(MAX);
EXEC EMPLOYEE_WITH_SALARY_RANGE 1000,7000,@OUT OUTPUT
PRINT(@OUT)

CREATE OR ALTER PROCEDURE Department_name_WITH_TRY_CATCH @ID INT,@DEPT VARCHAR(5)
AS
BEGIN TRY
insert into [Department name] values(@ID,@DEPT);
SELECT * FROM [Department name]
END TRY
BEGIN CATCH
PRINT('error DUPLICATE KEY '+CAST(@ID AS VARCHAR(5)))
END CATCH

EXEC Department_name_WITH_TRY_CATCH 108,MATH

DROP PROCEDURE EMPLOYEE_WITH_TRY_CATCH;
SELECT *FROM  STUDENT;
CREATE OR ALTER PROCEDURE UPDATE_DETAILS @ID INT, @NAME VARCHAR(30),@EMAIL VARCHAR(50)
AS
UPDATE STUDENT SET NAME=@NAME, EMAIL=@EMAIL WHERE ID=@ID;
GO