CREATE TABLE LOGS(ID VARCHAR(100),TRANSACTION_TIME DATETIME)
ALTER TABLE LOGS drop COLUMN ID 
ALTER TABLE LOGS ADD  ID UNIQUEIDENTIFIER
TRUNCATE TABLE LOGS
CREATE OR ALTER TRIGGER STUDENT_INSERT_TRIGGER
ON STUDENT 
AFTER INSERT 
AS
INSERT INTO LOGS VALUES(CURRENT_TIMESTAMP,NEWID());

INSERT INTO Student VALUES('Rahul',39110342,27,'rahul@gmail.com',8923473992,'2000-07-21','PHY',6)
SELECT * FROM LOGS
select * from Student
select USER_NAME()
select * from student where Id=3911345
Delete from student where name is NULL
insert into student(id, department) values(39110122,'PHY')
