
CREATE OR ALTER FUNCTION EXE_EMPLOYEE () RETURNS TABLE
AS	RETURN(SELECT * FROM EMPLOYEE)


CREATE TYPE SINGLE_COL AS TABLE(VALUES_ONE INT);

CREATE OR ALTER FUNCTION COUNT_OF_VAL_IN_RANGE (@TB_NAME SINGLE_COL READONLY ,@START INT,@END INT) 
RETURNS INT
AS
BEGIN
	DECLARE @SUBQUERY VARCHAR(MAX)
	RETURN(SELECT COUNT(*) FROM @TB_NAME)
END

DECLARE @TB_NAME SINGLE_COL
INSERT INTO @TB_NAME EXEC('SELECT SALARY FROM EMPLOYEE')
PRINT DBO.COUNT_OF_VAL_IN_RANGE(@TB_NAME,2000,7000)

EXEC DISPLAY_DETAILS;